# Generated by Django 5.1.3 on 2025-04-20 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cineBox', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('imagen', models.ImageField(upload_to='peliculas/')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peliculas', to='cineBox.sala')),
            ],
        ),
    ]
