# Generated by Django 5.1.3 on 2025-05-07 15:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cineBox', '0004_usuario_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='codigo_qr',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
