# Generated by Django 5.1.3 on 2025-05-09 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cineBox', '0005_reserva_codigo_qr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cineBox.horario'),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('tarjeta', 'Tarjeta'), ('paypal', 'PayPal'), ('efectivo', 'Efectivo')], max_length=50)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('fallido', 'Fallido')], default='pendiente', max_length=20)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('transaccion_id', models.CharField(blank=True, max_length=100, null=True)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='cineBox.reserva')),
            ],
        ),
    ]
