# Generated by Django 5.1.3 on 2025-05-12 14:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cineBox', '0006_alter_reserva_horario_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together={('usuario', 'sala', 'horario')},
        ),
    ]
