# Generated by Django 5.1.3 on 2025-05-26 01:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cineBox', '0008_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
