# Generated by Django 5.1.3 on 2025-05-26 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cineBox', '0009_horario_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='horario',
            name='hora',
            field=models.TimeField(),
        ),
    ]
